# Generated by Django 4.0.6 on 2022-09-17 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('nutrients', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ('-last_change_date',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Avatar URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ('-creation_date', 'uuid'),
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name="Artwork's contract address")),
                ('birthdate', models.CharField(max_length=100, verbose_name='Token id')),
                ('specie', models.CharField(max_length=100, null=True, verbose_name="Owner's wallet address")),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Avatar URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ('-last_change_date',),
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Value')),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Timestamp')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('source', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='restapi.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Measure',
                'verbose_name_plural': 'Measures',
                'ordering': ('-last_change_date',),
            },
        ),
    ]
